name: GitHub Snake Game (Custom)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install numpy matplotlib imageio

      - name: Set permissions for dist folder
        run: |
          mkdir -p dist
          chmod -R 777 dist
          ls -la dist  # Проверяем, что папка есть

      - name: Run Snake Generator
        run: python generate_snake.py

      - name: Check if dist folder exists
        run: ls -l dist || echo "⚠️ dist folder NOT found!"

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
